### ISSUE TITLE
no file 'data/2011_09_26\\2011_09_26_drive_0005_sync\\image_02\\data'

### ISSUE THREAD

**Issue by duboweidong** [Sharpiless/YOLOv11-DeepSort#1]
how can i solve it?
epSort/main_yolov11.py
Traceback (most recent call last):
  File "c:\Users\Administrator\Desktop\new\YOLOv11-DeepSort\main_yolov11.py", line 176, in <module>
    process_pipeline(data_path, drive, output_folder, model, infer_transform)
  File "c:\Users\Administrator\Desktop\new\YOLOv11-DeepSort\main_yolov11.py", line 143, in process_pipeline
    left_image_folder, left_image_files = load_image_pairs(data_path, drive)
  File "c:\Users\Administrator\Desktop\new\YOLOv11-DeepSort\main_yolov11.py", line 119, in load_image_pairs
    left_image_files = sorted(os.listdir(left_image_folder))
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'data/2011_09_26\\2011_09_26_drive_0005_sync\\image_02\\data'

**Comment by yuehuaz424** [comment]
同问
